### ISSUE TITLE
Adding h3-session to nuxt rc.10 leads to infinite loading 

### ISSUE THREAD

**Issue by BracketJohn** [wobsoriano/h3-session#1]
**Description**

When adding `h3-session` to nuxt 3, rc10 as a middleware like this:
```ts
import { SessionHandler } from 'h3-session'
import type { IncomingMessage, ServerResponse } from 'h3'
import type { Session } from 'h3-session'

export default SessionHandler({
  secret: 'keyboard cat',
  resave: false,
  saveUninitialized: true,
  cookie: { secure: true },
})
```

and then starting the app via `npm run dev`, the page just loads forever. After some time the request fails and another exception occurs on the server side: "headers cannot be set after response was sent to client"

**Comment by BracketJohn** [comment]
sorry @wobsoriano I hit "create" too soon by accident, the description is better now!

**Comment by etahamer** [comment]
@BracketJohn 

Have you found any solution?

**Comment by christopher4lis** [comment]
Also experiencing this right now, any solutions?

**Comment by etahamer** [comment]
> Also experiencing this right now, any solutions?

For time being I have cloned [https://github.com/koajs/generic-session/](https://github.com/koajs/generic-session/) and reworked it to support nuxt3. So if you have time to spare you may choose the same path. 

At the moment I cant share it, but if nothing changes from oficial nuxt, I may publish it in comming month or so

**Comment by BracketJohn** [comment]
I have sadly not found a solution using `h3-session`, instead I decided to implement it myself, creating a server middleware: https://v3.nuxtjs.org/guide/directory-structure/server#server-middleware

I will try to share the impl. as soon as possible as part of https://github.com/sidestream-tech/sidebase/ -> so follow their for updates (although I'll also add a post about it here (: )

**Comment by christopher4lis** [comment]
> I have sadly not found a solution using `h3-session`, instead I decided to implement it myself, creating a server middleware: https://v3.nuxtjs.org/guide/directory-structure/server#server-middleware

This is what I'm attempting to do right now as well. I'm not an expert in backend development like this, so if you have any pointers or resources on how to go about this, would love to hear them!

**Comment by BracketJohn** [comment]
Hey @christopher4lis - yeah, I want to open-source my implementation soon, probably as part of sidebase here: https://github.com/sidestream-tech/sidebase/

You can hop onto our discord to follow the development, someone else (elbrujolegal) was also there asking about auth (which shares some of the same problems): https://discord.gg/9MUHR8WT9B

**Comment by BracketJohn** [comment]
Hey @christopher4lis - it's done! 

github: https://github.com/sidebase/nuxt-session
npm: https://www.npmjs.com/package/@sidebase/nuxt-session

**Comment by BracketJohn** [comment]
also cc @etahamer

-> if it's helpful feel free to leave a star (:

**Comment by wobsoriano** [comment]
Late to the party but, fixed in https://github.com/wobsoriano/h3-session/releases/tag/v0.2.1

```ts
import type { Session } from 'h3-session'
declare module 'h3' {
  interface H3EventContext {
    session: Session
  }
}

export default defineEventHandler((event) => {
  console.log(event.context.session)
})
```

```ts
export default defineNuxtConfig({
  modules: ['h3-session/nuxt'],
  session: {
    secret: 'keyboard cats',
    resave: true,
    saveUninitialized: true,
    cookie: { secure: true },
  }
})
```
